# -*- coding: utf-8 -*-
"""build_learn.py — build the Learn-section data for the ML quiz site.

Reads a Hebrew course summary markdown (docs/learn_source.md), splits it into
sections (one per "## " heading), renders each to HTML, and emits:

    learn.js  ->  window.LEARN = [{id, title, html}, ...]

Static + offline (no runtime markdown parser, no CDN). Figures are optional: any
image referenced in the markdown as ![alt](images/xyz.png) is passed through as-is
(place the file under images/ yourself). Run:

    PYTHONUTF8=1 python tools/build_learn.py
"""
import os, re, json
import markdown

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SUMMARY = os.path.join(ROOT, "docs", "learn_source.md")
OUT_JS = os.path.join(ROOT, "learn.js")


def slugify(title):
    t = title.strip()
    m = re.match(r"^\[([a-z_]+)\]", t)   # optional [key] prefix chooses the id
    if m:
        return m.group(1)
    return "sec-" + re.sub(r"\W+", "-", t)[:24].strip("-")


def strip_key_prefix(title):
    return re.sub(r"^\[[a-z_]+\]\s*", "", title).strip()


def split_sections(md_text):
    lines = md_text.splitlines()
    page_title = "תרגול למידת מכונה"
    for ln in lines:
        if ln.startswith("# ") and not ln.startswith("## "):
            page_title = ln[2:].strip()
            break
    sections, cur_title, cur_buf = [], None, []
    for ln in lines:
        if ln.startswith("# ") and not ln.startswith("## "):
            continue
        if ln.startswith("## "):
            if cur_title is not None:
                sections.append((cur_title, "\n".join(cur_buf)))
            cur_title, cur_buf = ln[3:].strip(), []
        elif cur_title is not None:
            cur_buf.append(ln)
    if cur_title is not None:
        sections.append((cur_title, "\n".join(cur_buf)))
    return page_title, sections


_LIST_RE = re.compile(r"^(\s*)([-*+]|\d+\.)\s+")


def normalize_lists(md):
    out = []
    for ln in md.split("\n"):
        if _LIST_RE.match(ln):
            prev = out[-1] if out else ""
            p = prev.strip()
            if p and not _LIST_RE.match(prev) and not p.startswith("#") and not p.startswith("|"):
                out.append("")
        out.append(ln)
    return "\n".join(out)


def main():
    with open(SUMMARY, encoding="utf-8") as f:
        md_text = f.read()
    page_title, sections = split_sections(md_text)
    md = markdown.Markdown(extensions=["tables", "fenced_code", "sane_lists", "attr_list"])
    learn = []
    for title, body in sections:
        md.reset()
        sid = slugify(title)
        clean_title = strip_key_prefix(title)
        body_html = md.convert(normalize_lists(body.strip()))
        learn.append({"id": sid, "title": clean_title, "html": body_html})
    meta = {"generated": "auto", "chapters": len(learn), "images": 0}
    payload = (
        "/* AUTO-GENERATED by tools/build_learn.py — do not edit by hand. */\n"
        "window.LEARN = " + json.dumps(learn, ensure_ascii=False) + ";\n"
        "window.LEARN_META = " + json.dumps(meta, ensure_ascii=False) + ";\n"
    )
    with open(OUT_JS, "w", encoding="utf-8") as f:
        f.write(payload)
    print(f"page title : {page_title}")
    print(f"sections   : {len(learn)} -> {[s['id'] for s in learn]}")
    print(f"wrote      : {OUT_JS}")


if __name__ == "__main__":
    main()
